# tg_api_id: This is your Telegram API ID. You can get this by creating an application on the Telegram website.
tg_api_id: 28231674  # Replace with your actual API ID

# tg_api_hash: This is your Telegram API Hash. You can get this by creating an application on the Telegram website.
tg_api_hash: 432073238aba7664a77739dfec9ec449  # Replace with your actual API hash
tg_bot_token: 7779039550:AAGTRGKRs2dl1WeUFn74RLUB7j60GKipoL0
redis_broker_url: redis://redis:6379/0
redis_backend_url: redis://redis:6379/0
